I2C Light Sensor
viktorgino/headunit-desktop pull request #74
Opened 2023-01-25 07:21 UTC by aselafernando

Added a plugin to set night mode based on the value read from an i2c light sensor. Different sensors can be added through json files in the sensor folder.
Reading of the sensor can be disabled by setting the refresh interval to 0 (default).

It'll read the ambient light level from the specified register in the json file. In addition it has the ability to write a value to a configuration register each time, in case the module needs a write to turn it on.

This requires libi2c-dev be installed to compile (will need the wiki updated).

2023-01-25 22:33 UTC, viktorgino commented
Thanks @aselafernando! I'll have a proper look at it this weekend

2023-10-26 21:50 UTC, viktorgino requested changes
Thanks @aselafernando , just a few changes and good to go.
FYI back to working on this project again :)

2023-10-26 21:50 UTC, viktorgino commented on modules/i2c-light-sensor/i2c-light-sensor-plugin.cpp
> +    //m_pluginSettings.actions = QStringList() << "GetBrightness";
Could you remove these please?

2023-10-26 21:50 UTC, viktorgino commented on modules/i2c-light-sensor/i2c-light-sensor-plugin.cpp
> +    //qDebug() << "I2CLightSensor: event from " << id;
Remove?

2023-10-26 21:50 UTC, viktorgino commented on modules/i2c-light-sensor/i2c-light-sensor-plugin.cpp
> +        qDebug() << "I2CLightSensor: " << message;
Maybe use qCDebug?

2023-10-29 02:21 UTC, aselafernando commented
Made the changes, I also corrected a bug in the pro file where it wasn't copying the sensor json files over to the install directory.

I left ```m_pluginSettings.eventListeners = QStringList() << "AndroidAuto::connected";``` in as the plugin does rely on this event to ensure that as soon as a phone is connected it sets the night mode value.

2023-10-29 22:16 UTC, viktorgino commented
> Made the changes, I also corrected a bug in the pro file where it wasn't copying the sensor json files over to the install directory.
> 
> I left `m_pluginSettings.eventListeners = QStringList() << "AndroidAuto::connected";` in as the plugin does rely on this event to ensure that as soon as a phone is connected it sets the night mode value.

Perfect, thanks!

2023-10-29 22:16 UTC, merged